### Create a new user
POST {{host}}/api/chirps
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "body": "This is my first chirp!"
}

> {% client.global.set("chirp_id", response.body.id); %}

### Get all chirps
GET {{host}}/api/chirps
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get chirp by id
GET {{host}}/api/chirps/{{chirp_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}