### Login to get auth and refresh token
POST {{host}}/api/login

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.global.set("auth_token", response.body.token);
    client.global.set("refresh_token", response.body.refresh_token);
%}


### Refresh auth token with refresh token

POST {{host}}/api/refresh
Accept: application/json
Authorization: Bearer {{refresh_token}}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Revoke refresh token

POST {{host}}/api/revoke
Authorization: Bearer {{refresh_token}}